name: build liminix
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_vm_qemu_mips:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3

      - name: Build VM QEMU MIPS
        run: |
          # Enter the shell
          nix-build -I liminix-config=./examples/hello-from-qemu.nix --arg device "import ./devices/qemu" -A outputs.default
